---
-
  include_vars: "{{ ansible_os_family }}.yml"
  name: "Include OS-Specific variables"
-
  include_tasks: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
-
  include_tasks: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"
-
  include_tasks: nginx.yml
