---
-
  name: "Download WordPress"
  get_url:
    url: "{{ wp_url }}"
    dest: /tmp
    force: no
-
  name: "Extract archive"
  unarchive:
    src: "{{ wp_tar_file }}"
    dest: "{{ app_root }}"
    copy: no
    extra_opts:
      - "--strip-components=1"
    group: "{{ nginx_user }}"
    owner: "{{ nginx_user }}"

-
  name: "Set up wordpress file permission"
  file:
   path: "{{item}}"
   state: directory
   mode: 0755
  with_items:
  - "{{ app_root }}/wp-admin"
  - "{{ app_root }}/wp-content"
  - "{{ app_root }}/wp-includes"

- name: Remove wordpress download archive
  file:
    path: "{{ wp_tar_file }}"
    state: absent
