---
-
  package:
    name: "{{item}}"
    state: present
  name: "Install test dependencies"
  tags:
    - install_dependencies
  with_items: "{{ test_required_libs  }}"
-
  group:
    name: "{{ tomcat_group }}"
    system: true
  name: "Create tomcat group"
  tags:
    - create_tomcat_group
-
  name: "Create tomcat user"
  tags:
    - create_tomcat_user
  user:
    createhome: true
    generate_ssh_key: true
    group: "{{ tomcat_group }}"
    home: "{{tomcat_home_dir}}"
    name: "{{ tomcat_user }}"
    shell: /bin/bash
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    system: true
-
  become_user: "{{ tomcat_user }}"
  name: "Add ssh config"
  tags:
    - add_ssh_config
  template:
    dest: "{{tomcat_home_dir}}/.ssh/config"
    mode: 256
    src: ssh-config.j2
-
  name: "Download and extract tomcat archive"
  tags:
    - download_extract
  unarchive:
    copy: false
    dest: "{{tomcat_home_dir}}"
    extra_opts:
      - "--strip-components=1"
    group: "{{ tomcat_group }}"
    mode: 0750
    owner: "{{ tomcat_user }}"
    src: "{{ tomcat_url }}"
-
  become_user: "{{ tomcat_user }}"
  name: "Create tomcat-users.xml"
  tags:
    - apply_tomcat_user_role
  template:
    dest: "{{tomcat_home_dir}}/conf/tomcat-users.xml"
    src: tomcat-users.xml.j2
-
  become_user: "{{ tomcat_user }}"
  name: "Remove everything under tomcat webapps directory"
  shell: "rm -rf {{tomcat_home_dir}}/webapps/*"
  args:
    warn: false
  tags:
    - remove_webapps_file
-
  become_user: "{{ tomcat_user }}"
  get_url:
    dest: "{{tomcat_home_dir}}/webapps/ROOT.war"
    mode: 416
    url: "{{ jenkins_url }}"
  name: "Download Jenkins war file"
  tags:
    - get_jenkins
-
  become_user: "{{ tomcat_user }}"
  name: "Adding JENKINS_HOME in tomcat configuration"
  tags:
    - add_jenkins_home_config
  template:
    dest: "{{tomcat_home_dir}}/conf/context.xml"
    src: conf-context.xml.j2
-
  file:
    dest: "{{ tomcat_app_path }}"
    src: "{{ tomcat_home_dir }}"
    state: link
  name: "Symlink Tomcat to current version"
  tags:
    - create_app_link
-
  name: "Create systemd service script for Tomcat"
  notify:
    - "reload systemd"
    - "enable tomcat"
    - "restart tomcat"
  tags:
    - systemd_script_install
  template:
    dest: /lib/systemd/system/tomcat.service
    src: tomcat.service.j2
