---
-
  name: "Install necssary package"
  yum:
    name: wget
    state: installed
-
  command: "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" \"{{download_url}}\" -P /tmp"
  name: "Download java source file"
  args:
    warn: False
  tags:
    - download_java
-
  name: "RedHat | Install Java Oracle"
  register: rpm_installation
  yum:
    name: "{{java_package_path}}"
    state: installed
-
  alternatives:
    link: /usr/bin/java
    name: java
    path: "{{ java_home }}/bin/java"
  become: true
  name: "Set Oracle Java version as default"
  tags:
    - make_default
-
  file:
    path: "{{ item }}"
    state: absent
  name: "Remove artifact"
  tags:
    - remove_artifact
  with_items:
    - "{{ java_package_path }}"
